# -*- coding: utf-8 -*-
"""issue_4_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbpMQUC5yVIWRm5Th52bmZ_dNa1dhvoU
"""

from one_hot_encoder import fit_transform
import pytest


def test_wrong_input():
    with pytest.raises(TypeError):
        fit_transform(111)


def test_dota2_spirits():
    spirits = ["Void", "Ember", "Storm", "Earth"]
    expected = [
        ("Void", [0, 0, 0, 1]),
        ("Ember", [0, 0, 1, 0]),
        ("Storm", [0, 1, 0, 0]),
        ("Earth", [1, 0, 0, 0]),
    ]
    assert fit_transform(spirits) == expected


def test_avito_courses():
    courses = ["python", "sql", "stats"]
    expected = [("python", [0, 0, 1]), ("sql", [0, 1, 0]), ("stats", [1, 0, 0])]
    assert fit_transform(courses) == expected


def test_students():
    students = ["Alex", "Ilya", "Max", "Peter"]
    expected = [
        ("Alex", [0, 0, 0, 1]),
        ("Ilya", [0, 0, 1, 0]),
        ("Max", [0, 1, 0, 0]),
        ("Peter", [1, 0, 0, 0]),
    ]
    assert fit_transform(students) == expected