# -*- coding: utf-8 -*-
"""issue_3_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbpMQUC5yVIWRm5Th52bmZ_dNa1dhvoU
"""

from one_hot_encoder import fit_transform
import unittest


class TestFitTransform(unittest.TestCase):
    def test_catch_exception(self):
        n = 111
        try:
            fit_transform(n)
        except TypeError:
            self.assertRaises(TypeError)

    def test_dota2_spirits(self):
        spirits = ["Void", "Ember", "Storm", "Earth"]
        actual = fit_transform(spirits)
        expected = [
            ("Void", [0, 0, 0, 1]),
            ("Ember", [0, 0, 1, 0]),
            ("Storm", [0, 1, 0, 0]),
            ("Earth", [1, 0, 0, 0]),
        ]
        self.assertEqual(actual, expected)

    def test_avito_courses(self):
        courses = ["python", "sql", "stats"]
        actual = fit_transform(courses)
        expected = [("python", [0, 0, 1]), ("sql", [0, 1, 0]), ("stats", [1, 0, 0])]
        self.assertEqual(actual, expected)

    def test_games(self):
        pc_games = ["Minecraft"]
        actual = fit_transform(pc_games)
        console_games = [
            ("Minecraft", [0, 0, 1]),
            ("Terraria", [0, 1, 0]),
            ("Battlefield", [1, 0, 0]),
        ]
        self.assertNotIn(actual, console_games)