# -*- coding: utf-8 -*-
"""issue_2_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IbpMQUC5yVIWRm5Th52bmZ_dNa1dhvoU
"""

from morse import decode
import pytest


@pytest.mark.parametrize(
    "dot_dash, message",
    [("... --- ...", "SOS"), ("", ""), (".---- ..--- ...--", "123")],
)
def test_decode(dot_dash, message):
    assert decode(dot_dash) == message